```{r}
df <- read.csv('../datasets/Economist_Assignment_Data.csv')
head(df)
```
```{r}
str(df)
```
```{r}
summary(df)
```
```{r}
library(ggplot2)
pl <- ggplot(df, aes(x=CPI, y=HDI, color=Region)) + geom_point()
pl
```
```{r}
pl <- ggplot(df, aes(x=CPI, y=HDI, color=Region)) + geom_point(size=3, shape=1)
pl
```
```{r}
pl <- ggplot(df, aes(x=CPI, y=HDI, color=Region)) + geom_point(size=3, shape=1) + geom_smooth(aes(group=1))
pl
```
```{r}
pl <- ggplot(df, aes(x=CPI, y=HDI, color=Region)) + geom_point(size=3, shape=1)
pl2 <- pl + geom_smooth(aes(group=1), method='lm', formula=y~log(x), se=F, color='red')
pl2
```
```{r}
pl3 <- pl2 + geom_text(aes(label=Country))
pl3
```
```{r}
points.to.label <- c("Russia", "Venezuela", "Iraq", "Myanmar", "Sudan",
                   "Afghanistan", "Congo", "Greece", "Argentina", "Brazil",
                   "India", "Italy", "China", "South Africa", "Spane",
                   "Botswana", "Cape Verde", "Bhutan", "Rwanda", "France",
                   "United States", "Germany", "Britain", "Barbados", "Norway", "Japan",
                   "New Zealand", "Singapore")
```
```{r}
pl3 <- pl2 + geom_text(aes(label=Country), color='gray20', data=subset(df, Country %in% points.to.label), check_overlap=T)
pl3
```
```{r}
pl4 <- pl3 + scale_x_continuous(name='Corruption Perceptions Index, 2011 (10=least corrupt)', limits= c(0.9, 10.5), breaks=1:10)
pl4
```
```{r}
pl5 <- pl4 + scale_y_continuous(name='Human Development Index, 2011 (1=Best)', limits=c(0.2, 1.0))
pl5
```
```{r}
pl5 + ggtitle('Corruption and Human Development')
```
