```{r}
df <- read.csv('../datasets/adult_sal.csv')
head(df)
```
```{r}
str(df)
```

#####
**Data cleaning**

```{r}
library(dplyr)
df <- select(df, -X)
```
```{r}
table(df$type_employer)
```
```{r}
group_emp <- function(job){
  if(job == 'Local-gov' | job == 'State-gov'){
    return('SL-gov')
  } else if(job == 'Self-emp-inc' | job == 'Self-emp-not-inc'){
    return('self-emp')
  }else{
    return(job)
  }
}
df$type_employer <- sapply(df$type_employer, group_emp)
```
```{r}
unemp <- function(job){
  if(job == 'Never-worked' | job == 'Without-pay'){
    return('Unemployed')
  }else{
    return(job)
  }
}
df$type_employer <- sapply(df$type_employer, unemp)
```
```{r}
table(df$type_employer)
```
```{r}
table(df$marital)
```
```{r}
group_marital <- function(mar){
  mar <- as.character(mar)
  
  if(mar == 'Separated' | mar == 'Divorced' | mar == 'Widowed'){
    return('Not-married')
  }else if(mar == 'Never-married'){
    return(mar)
  }else{
    return('Married')
  }
}

df$marital <- sapply(df$marital, group_marital)
table(df$marital)
```
```{r}
table(df$country)
```
```{r}
Asia <- c('China','Hong','India','Iran','Cambodia','Japan', 'Laos' ,
          'Philippines' ,'Vietnam' ,'Taiwan', 'Thailand')

North.America <- c('Canada','United-States','Puerto-Rico' )

Europe <- c('England' ,'France', 'Germany' ,'Greece','Holand-Netherlands','Hungary',
            'Ireland','Italy','Poland','Portugal','Scotland','Yugoslavia')

Latin.and.South.America <- c('Columbia','Cuba','Dominican-Republic','Ecuador',
                             'El-Salvador','Guatemala','Haiti','Honduras',
                             'Mexico','Nicaragua','Outlying-US(Guam-USVI-etc)','Peru',
                            'Jamaica','Trinadad&Tobago')
Other <- c('South')
```
```{r}
group_country <- function(ctry){
  if(ctry %in% Asia){
    return('Asia')
  }else if(ctry %in% North.America){
    return('North-America')
  }else if(ctry %in% Europe){
    return('Europe')
  }else if(ctry %in% Latin.and.South.America){
    return('Latin-and-South-America')
  }else{
    return('Other')
  }
}
df$country <- sapply(df$country, group_country)
table(df$country)
```
```{r}
str(df)
```
```{r}
df$type_employer <- factor(df$type_employer)
df$education <- factor(df$education)
df$marital <- factor(df$marital)
df$occupation <- factor(df$occupation)
df$relationship <- factor(df$relationship)
df$race <- factor(df$race)
df$sex <- factor(df$sex)
df$country <- factor(df$country)
df$income <- factor(df$income)
str(df)
```

#####
**Missing data**

```{r}
library(Amelia)
df[df == '?'] <- NA
```
```{r}
table(df$type_employer)
```
```{r}
df$type_employer <- factor(df$type_employer)
df$marital <- factor(df$marital)
df$occupation <- factor(df$occupation)
df$country <- factor(df$country)
str(df)
```
```{r}
missmap(df)
```
```{r}
df <- na.omit(df)
```
```{r}
missmap(df)
```

#####
**EDA**

```{r}
str(df)
```
```{r}
library(ggplot2)
library(dplyr)
```
```{r}
ggplot(df, aes(age)) + geom_histogram(aes(fill=income), color='black', binwidth=1) + theme_bw()
```
```{r}
ggplot(df, aes(hr_per_week)) + geom_histogram() + theme_bw()
```
```{r}
names(df)[names(df) == 'country'] <- 'region'
```
```{r}
ggplot(df, aes(region)) + geom_bar(aes(fill=income), color='black') + theme_bw() + theme(axis.text.x = element_text(angle=90, hjust=1))
```

#####
*Build the model**

```{r}
library(caTools)
set.seed(101)
sample <- sample.split(df$income, SplitRatio=0.7)
train <- subset(df, sample==TRUE)
test <- subset(df, sample==FALSE)
```
```{r}
model <- glm(income ~. , family=binomial(logit), data=train)
summary(model)
```
```{r}
new.step.model <- step(model)
```
```{r}
summary(new.step.model)
```
```{r}
test$predicted.income <- predict(model, newdata=test, type='response')
```
```{r}
table(test$income, test$predicted.income > 0.5)
```
```{r}
# f1-score
(6372+1423)/(6372+1423+548+872)
```
```{r}
# recall
6732/(6372+548)
```
```{r}
# precision
6732/(6372+872)
```
