```{r}
df <- read.csv('../datasets/loan_data.csv')
head(df)
```
```{r}
str(df)
```
```{r}
summary(df)
```
```{r}
df$purpose <- factor(df$purpose)
df$inq.last.6mths <- factor(df$inq.last.6mths)
df$delinq.2yrs <- factor(df$delinq.2yrs)
df$pub.rec <- factor(df$pub.rec)
df$not.fully.paid <- factor(df$not.fully.paid)
df$credit.policy <- factor(df$credit.policy)
str(df)
```
```{r}
library(ggplot2)

ggplot(df, aes(x=fico)) + geom_histogram(aes(fill=not.fully.paid), color='black', bins=40)
```
```{r}
ggplot(df, aes(x=purpose)) + geom_bar(aes(fill=not.fully.paid), position='dodge') + theme(axis.text.x=element_text(angle=90))
```
```{r}
ggplot(df, aes(x=int.rate, y=fico)) + geom_point(aes(color=not.fully.paid), alpha=0.3) + theme_bw()
```
```{r}
library(caTools)

set.seed(101)
sample <- sample.split(df$not.fully.paid, SplitRatio=0.7)

train <- subset(df, sample == TRUE)
test <- subset(df, sample == FALSE)
```

```{r}
library(e1071)

tune.results <- tune(svm, train.x=not.fully.paid~. , data=train, kernel='radial', ranges=list(cost=c(1, 10), gamma=c(0.1, 1)))

summary(tune.results)
```
```{r}
tuned.svm <- svm(not.fully.paid ~. , data=train, kernel='radial', cost=1, gamma=0.1)
summary(tuned.svm)
```
```{r}
predicted.values <- predict(tuned.svm, test[1:13])
table(predicted.values, test$not.fully.paid)
```
