```{r}
library(ISLR)
df <- College
head(df)
```
```{r}
str(df)
```
```{r}
summary(df)
```
```{r}
any(is.na(df))
```
```{r}
library(ggplot2)
ggplot(df, aes(x=Room.Board, y=Grad.Rate)) + geom_point(aes(color=Private))
```
```{r}
ggplot(df, aes(F.Undergrad)) + geom_histogram(aes(fill=Private), color='black', bins=50)
```
```{r}
ggplot(df, aes(x=Grad.Rate)) + geom_histogram(aes(fill=Private), color='black', bins=50)
```
```{r}
subset(df, Grad.Rate > 100)
```
```{r}
df['Cazenovia College', 'Grad.Rate'] <- 100
```

```{r}
ggplot(df, aes(x=Grad.Rate)) + geom_histogram(aes(fill=Private), color='black', bins=50)
```
```{r}
library(caTools)

set.seed(101)
sample <- sample.split(df$Private, SplitRatio=0.7)

train <- subset(df, sample == TRUE)
test <- subset(df, sample == FALSE)
```

#####
**Decision tree**

```{r}
library(rpart)
tree <- rpart(Private ~. , method='class', data=train)
```

```{r}
tree.preds <- predict(tree, test)
head(tree.preds)
```
```{r}
tree.preds <- as.data.frame(tree.preds)

joiner <- function(x){
    if (x>=0.5){
        return('Yes')
    }else{
        return("No")
    }
}
tree.preds$Private <- sapply(tree.preds$Yes, joiner)
```

```{r}
head(tree.preds)
```
```{r}
table(tree.preds$Private, test$Private)
```
```{r}
library(rpart.plot)
prp(tree)
```

#####
**Random forest**

```{r}
library(randomForest)
rf.model <- randomForest(Private ~. , data=train, importance=TRUE)
```

```{r}
rf.model$confusion
```
```{r}
rf.model$importance
```
```{r}
rf.preds <- predict(rf.model, test)
```

```{r}
table(rf.preds, test$Private)
```
