```{r}
#install.packages('ISLR')
```
```{r}
library(ISLR)
head(Caravan)
```
```{r}
str(Caravan)
```
```{r}
summary(Caravan$Purchase)
```
```{r}
any(is.na(Caravan))
```
```{r}
var(Caravan[,1])
```
```{r}
var(Caravan[,2])
```
```{r}
purchase <- Caravan[, 86]
standardized.Caravan <- scale(Caravan[, -86])
print(var(standardized.Caravan[, 1]))
print(var(standardized.Caravan[, 2]))
```
```{r}
test.index <- 1:1000
test.data <- standardized.Caravan[test.index, ]
test.purchase <-purchase[test.index]
```
```{r}
train.data <- standardized.Caravan[-test.index, ]
train.purchase <- purchase[-test.index]
```

```{r}
library(class)
set.seed(101)

predicted.purchase <- knn(train.data, test.data, train.purchase, k=1)
head(predicted.purchase)
```
```{r}
misclass.error <- mean(test.purchase != predicted.purchase)
misclass.error
```
```{r}
# choosing a k value
predicted.purchase <- NULL
error.rate <- NULL

for(i in 1:20){
  set.seed(101)
  predicted.purchase <- knn(train.data, test.data, train.purchase, k=i)
  error.rate[i] <- mean(test.purchase != predicted.purchase)
}
print(error.rate)
```
```{r}
library(ggplot2)
k.values <- 1:20
error.df <- data.frame(error.rate, k.values)
error.df
```
```{r}
ggplot(error.df, aes(k.values, error.rate)) + geom_point() + geom_line(lty='dotted', color='red')
```
