#####
Creating a matrix

```{r}
v <- 1:10
v
```
```{r}
matrix(v)
```
```{r}
matrix(v, nrow=2)
```
```{r}
matrix(v, byrow=TRUE, nrow=2)
```
```{r}
goog <- c(450, 451, 452, 445, 468)
msft <- c(230, 231, 232, 233, 220)

stocks <- c(goog, msft)
stocks
```
```{r}
stock.matrix <- matrix(stocks, byrow=T, nrow=2)
stock.matrix
```
```{r}
days <- c('Mon', 'Tue', 'Wed', 'Thu', 'Fri')
st.names <- c('GOOG', 'MSFT')

colnames(stock.matrix) <- days
rownames(stock.matrix) <- st.names

stock.matrix
```
#####
Matrix arithmetic

```{r}
mat <- matrix(1:25, byrow=T, nrow=5)
mat
```
```{r}
mat * 2
```
```{r}
mat / 2
```
```{r}
mat ^ 2
```
```{r}
1/mat
```
```{r}
mat > 15
```
```{r}
mat[mat > 15]
```
```{r}
mat %*% mat # true multiplication matrix by matrix
```
#####
Matrix operations

```{r}
goog <- c(450, 451, 452, 445, 468)
msft <- c(230, 231, 232, 233, 220)

stocks <- c(goog, msft)

stock.matrix <- matrix(stocks, byrow=T, nrow=2)

days <- c('Mon', 'Tue', 'Wed', 'Thu', 'Fri')
st.names <- c('GOOG', 'MSFT')

colnames(stock.matrix) <- days
rownames(stock.matrix) <- st.names

stock.matrix
```
```{r}
colSums(stock.matrix)
```
```{r}
rowSums(stock.matrix)
```
```{r}
rowMeans(stock.matrix)
```
```{r}
FB <- c(111, 112, 113, 120, 145)
tech.stocks <- rbind(stock.matrix, FB)
tech.stocks
```
```{r}
avg <- rowMeans(tech.stocks)
avg
```
```{r}
tech.stocks <- cbind(tech.stocks, avg)
tech.stocks
```
#####
Matrix indexing and selection

```{r}
v <- c(1, 2, 3, 4, 5)
v[2]
```
```{r}
mat <- matrix(1:50, byrow=T, nrow=5)
mat
```
```{r}
mat[1,]
```
```{r}
mat[2, 5]
```
```{r}
mat[1:3,]
```
```{r}
mat[1:2, 1:3]
```
```{r}
mat[, 9:10]
```
```{r}
mat[2:3, 5:6]
```
#####
Factor and categorical matrices

```{r}
animal <- c('d', 'c', 'd', 'c', 'c')
id <- c(1, 2, 3, 4, 5)
factor(animal)
```
```{r}
fact.ani <- factor(animal)
```
```{r}
temps <- c('cold', 'med', 'hot', 'hot', 'hot', 'cold', 'med')
temps
```
```{r}
fact.temp <- factor(temps, ordered=T, levels=c('cold', 'med', 'hot'))
fact.temp
```
```{r}
summary(fact.temp)
```
```{r}
summary(temps)
```
